/**
 * In-process registry of synthetic-actor secrets (Phase 3 / Step 40c-v3,
 * Decision G.1 + G.3). Holds the password generated by `synthesize-actor`
 * and the JWT obtained by `establish-actor-session`, keyed by `actor_id`.
 *
 * Lifecycle: constructed at the start of one Mode B Bedrock loop run; lives
 * inside the `runBedrockLoopBranchModeB(...)` closure; `clearAll()` is called
 * in the `try / finally` cleanup phase (V21) — on success AND on loop crash.
 *
 * Trust model (CLAUDE.md §Secrets):
 *  - Passwords + JWTs are held HERE only, never serialized to artifact / log /
 *    trace. Only digests (sha256) cross the boundary into `actor-sessions.json`
 *    (Decision G.2).
 *  - This file is in `src/core/sandbox/` so it stays Finding-free (V13 import-
 *    graph guard). It imports zero project types other than this file's own.
 *  - The registry does NOT expose a `serialize()` method. Test access goes
 *    through the test-only `entriesForTest()` getter which is documented as
 *    such; tests assert the registry is empty after `clearAll()`.
 */

export interface ActorSecret {
  readonly actor_id: string;
  readonly email: string;
  readonly password: string;
  /** Set after `establish-actor-session` signs the actor in. */
  readonly access_token?: string;
  /** Optional session metadata for cleanup signOut + report rendering. */
  readonly expires_at?: string;
}

export class ActorSecretRegistry {
  private readonly entries = new Map<string, ActorSecret>();

  /** Record a freshly-synthesized actor's email + password. */
  recordActor(input: {
    readonly actor_id: string;
    readonly email: string;
    readonly password: string;
  }): void {
    this.entries.set(input.actor_id, {
      actor_id: input.actor_id,
      email: input.email,
      password: input.password,
    });
  }

  /** Set the JWT obtained from `signInWithPassword`. */
  recordSession(input: {
    readonly actor_id: string;
    readonly access_token: string;
    readonly expires_at?: string;
  }): void {
    const existing = this.entries.get(input.actor_id);
    if (existing === undefined) {
      throw new Error(
        `ActorSecretRegistry: cannot record session for unknown actor "${input.actor_id}" — call recordActor() first`,
      );
    }
    this.entries.set(input.actor_id, {
      ...existing,
      access_token: input.access_token,
      ...(input.expires_at !== undefined ? { expires_at: input.expires_at } : {}),
    });
  }

  /** Read an actor's secrets. Returns `undefined` for unknown ids. */
  get(actorId: string): ActorSecret | undefined {
    return this.entries.get(actorId);
  }

  /** Wipe every entry. Called in `runBedrockLoopBranchModeB`'s `finally`. */
  clearAll(): void {
    this.entries.clear();
  }

  /** Test-only getter for V21 assertions. Production code does NOT use this. */
  entriesForTest(): ReadonlyArray<ActorSecret> {
    return Array.from(this.entries.values());
  }
}
